# Generated by Django 3.2.12 on 2022-04-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image_full', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image_2pieces', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image_4pieces', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image_8pieces', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('energy_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squirrels', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_small', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_big', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diameter_small', models.IntegerField()),
                ('diameter_big', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
