# Generated by Django 3.2.12 on 2022-04-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='avaible',
            field=models.BooleanField(default=True, verbose_name='Есть ли в наличии'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Название для URL-адреса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter_big',
            field=models.IntegerField(verbose_name='Диаметр большой пиццы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter_small',
            field=models.IntegerField(verbose_name='Диаметр маленькой пиццы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Энерг.ценность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2pieces',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение разделенное на 2 куска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4pieces',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение разделенное на 4 куска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_8pieces',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение разделенное на 8 кусков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_full',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Полное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Название для URL-адреса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='squirrels',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_big',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес большой пиццы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_small',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес маленькой пиццы'),
        ),
    ]
