# Generated by Django 3.2.12 on 2022-04-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='div',
            field=models.CharField(db_index=True, default='', editable=False, max_length=100, verbose_name='ID для div-a'),
        ),
    ]
