# Generated by Django 3.2.12 on 2022-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_2pieces',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4pieces',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_8pieces',
        ),
        migrations.AlterField(
            model_name='product',
            name='div',
            field=models.CharField(max_length=100, verbose_name='ID для div-a'),
        ),
    ]
